---
version: '2'
services:
  frontend:
    image: onelove/frontend
    volumes:
      - ./projects/frontend:/usr/src/app
    command: ./bin/dev.sh
    ports:
      - "8080:8080"

  backend:
    image: python:2-onbuild
    volumes:
      - ./projects/backend:/usr/src/app
      - /tmp/.cache:/root/.cache
    command: ./bin/dev.sh
    ports:
      - "5000:5000"
    links:
      - mongodb:mongodb

  worker:
    image: python:2-onbuild
    volumes:
      - ./projects/backend:/usr/src/app
      - /tmp/.cache:/root/.cache
    command: ./bin/worker_dev.sh

  mongodb:
    image: mongo:latest
