# Please do not edit this file for additional fstabs
# Use /cbsd/jails-fstab/fstab.local instead
/cbsd/jails-data/PROJECT-data/etc /etc nullfs rw 0 0
/cbsd/jails-data/PROJECT-data/root /root nullfs rw 0 0
/cbsd/jails-data/PROJECT-data/tmp /tmp nullfs rw 0 0
/cbsd/jails-data/PROJECT-data/usr/home /usr/home nullfs rw 0 0
/cbsd/jails-data/PROJECT-data/usr/local /usr/local nullfs rw 0 0
/cbsd/jails-data/PROJECT-data/usr/compat /usr/compat nullfs rw 0 0
/cbsd/jails-data/PROJECT-data/var /var nullfs rw 0 0
PWD /usr/home/devel/workdir nullfs rw 0 0
#
